server:
  port: 8000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://i8a703.p.ssafy.io:8761/eureka

jwt:
  token: jwt.secret=PorkCurtletFriedChickenSundubuJJigaeGrilledPorkBelly


spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      routes:
        - id: uniqueCheck
          uri: http://i8a703.p.ssafy.io:8012/
          predicates:
            - Path=/check/**
        - id: sessionFunction
          uri: http://i8a703.p.ssafy.io:8013/
          predicates:
            - Path=/sessionFunction/**
        - id: board
          uri: http://i8a703.p.ssafy.io:8011/
          predicates:
            - Path=/board/**
        - id: member
          uri: http://i8a703.p.ssafy.io:8012/
          predicates:
            - Path=/member/**
        - id: session
          uri: http://i8a703.p.ssafy.io:8014/
          predicates:
            - Path=/session/**
        - id: comment
          uri: http://i8a703.p.ssafy.io:8011/
          predicates:
            - Path=/comment/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://i8a703.p.ssafy.io:3306/project1db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    password: cossafyco
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
    database: mysql
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
  data:
    web:
      pageable:
        one-indexed-parameters: 'true'