server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://i8a703.p.ssafy.io:8761/eureka


spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      routes:
        - id: sessionFunction
          uri: http://i8a703.p.ssafy.io:8013/
          predicates:
            - Path=/sessionFunction/**
        - id: board
          uri: http://i8a703.p.ssafy.io:8011/
          predicates:
            - Path=/board/**
        - id: member
          uri: http://i8a703.p.ssafy.io:8012/
          predicates:
            - Path=/member/**
        - id: session
          uri: http://i8a703.p.ssafy.io:8014/
          predicates:
            - Path=/session/**
